@startuml
class com.mycompany.eva3_5_controlar_excepciones.EVA3_5_CONTROLAR_EXCEPCIONES
class java.util.Scanner
com.mycompany.eva3_5_controlar_excepciones.EVA3_5_CONTROLAR_EXCEPCIONES ..> java.util.Scanner
class EVA3_5_CONTROLAR_EXCEPCIONES{
main(args: String[]):void
}
@enduml